services:
  vulnerable-spa:
    image: kremlsa/vulnerable-spa:latest
    container_name: vulnerable-spa-app
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      WAF_LEVEL: NONE
    # Ограничение ресурсов
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          memory: 128M

    # Ограничение логов, чтобы диск не переполнился
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
